### PR TITLE
Retrieve historical observations

### PR DESCRIPTION
**Pull request by jonocarroll**
- added NEWS item to potential v0.1.5.
- added @jonocarroll as author.
- added tests with 100% coverage of exported function.
  (internal functions untested so far)
- no additional dependencies.
- no significant NOTEs.
- version requires bump in DESCRIPTION.

Most of the URL parameters for a given resource were straightforward enough to obtain. I eventually figured out that `p_nccObsCode` was the observation type, selecting from just four undocumented options. The `p_c` URL parameter I still can't decode, but as per [this suggestion](https://stackoverflow.com/a/20737688/4168169) it can be identified with one more download.

I consider this data to be freely available via download direct from the BOM site, so all this function is doing is making that easier. That said, you may wish to introduce a `Sys.sleep()` to prevent overuse.

BOM seems to have some pretty extensive records... `ADELAIDE (WEST TERRACE / NGAYIRDAPIRA)` seems to go back to the 1880's.

adelaidehistorical

### CODE REVIEW

**Comment by adamhsparks** [comment]
Fantastic! This is a great addition to the package, thanks @jonocarroll. 

I've merged this into the devel branch for testing and made some changes. Could you take a look?
https://github.com/ropensci/bomrang/commit/341802195be4a5773a9be31fbc8608b99446a33b

A few questions:

- Are you using a development version of roxygen2? I don't think I have that on any of my machines.

- I moved the internal functions to `internal_functions.R` with the rest of our internal functions and added `@noRd` tags to them since I get an error when building documentation and since they're internal, they don't need to be exported or documented. Was there a reason for documenting them? 

- Do you want to add the entry for `get_historical()` to the bomrang.Rmd vignette?

**Comment by jonocarroll** [comment]
That looks great!

* I am using the dev version of roxygen2 -- I'll reinstall the CRAN version before resubmitting. I don't think it was for any particular feature, I probably installed a dev version of a tidyverse or r-lib package.

* No worries re moving the internal functions. I didn't spot that you had a place for them, and figured all-in-one was clearer for the PR anyway. I like to document internal functions for the developer's benefit (usually me). I forgot to `@noRd` them but did notice the check `NOTE`s.

* This can perhaps be left for refactoring, but _should_ those functions be split out? I felt that they "did their own thing" but the reason for moving them out wasn't that they're reused -- they could just as easily be inlined into `get_historical`. I went for split out because a) they're cleaner to unit test, and b) they're cleaner to wrap in a `try`-like framework. We should also discuss how defensive you want to be about internal failures like network dropout, etc...

* I'll add unit tests for the internal functions.

* Thanks for fixing the `.rda` `NOTE` -- I saw that you had used the file internally before but I perhaps didn't copy over the entire implementation.

* I'll definitely add to the vignette. Again it was a tradeoff between doing too much work in a potentially rejected PR.

Give me a week or so and I'll have all of that updated.

**Comment by adamhsparks** [comment]
Thanks, sounds good to me. No hurry, I'm rather busy this week. Just had a few moments with some coffee this AM to go through your PR.

About network requests, I've started incorporating `tryCatch()` for my queries in some packages for server responses and whatnot for at least some assurance of gracefully handling server or network issues most easily to begin with. Or using `crul` and checking server responses before sending the request as well. That should be doable with `httr`?

I had a thought on handling the CSV files. `readr` is already an import, you can use it in `.get_zip_and_load()` and skip the unzipping portion and with large volumes? We also import `data.table` as well. So there are two options there for importing the CSV that might be faster than the `read.csv()` is.

**Comment by jonocarroll** [comment]
Cheers, I'll check out what `readr` does for zipped files -- there's a `.txt` in the file too though, so that may cause issues. [This](https://stackoverflow.com/questions/49807256/does-readr-read-csv-allow-one-to-specific-the-specific-file-in-a-zip) suggests it may be possible via `unz`, but I'll need to double check whether or not the filename is known before unzipping.

The data aren't huge, so performance won't be such an issue.

**Comment by adamhsparks** [comment]
Ah. Didn't realise there was a text file in there too. I'd keep as is.

-- 
Adam H Sparks

**Comment by adamhsparks** [comment]
I've added you as a collaborator so you can work from the `devel` branch if you'd like to and keep my changes.

Whatever you find easiest.

**Comment by jonocarroll** [comment]
Cheers and thanks, I'll work from `devel` to preserve your changes.

FYI, you can change the base branch of a PR and merge that. As it stands this PR is now behind its target so I'll close it.

**Comment by adamhsparks** [comment]
Yes, I just merged it locally with `devel` and worked on it there. I should change the default target for PRs.

**Pull request closed without merging**
