### PR TITLE
try running test on bulletins

### PR DESCRIPTION
**Pull request by HughParsonage**

### CODE REVIEW

**Comment by adamhsparks** [comment]
Still fails. Any ideas what's going on? I can run tests on Linux locally and it passes, but not Travis.

**Comment by HughParsonage** [comment]
No idea yet sorry 😞 

I'm guessing there might be a 'warning' in those tests (maybe not an actual warning, just the word warning) that is written to the logs, thus triggering a failure on Travis.

**Comment by HughParsonage** [comment]
I wish `dplyr` and `readr` were faster to compile, yikes. Takes nearly 20 minutes just to install deps.

**Comment by HughParsonage** [comment]
HI @adamhsparks still unsure but maybe the information that's now at the bottom of the travis logs can help?

**Comment by adamhsparks** [comment]
Thanks, I've been trying to get that information to show up.

Looks like it's a connectivity issue to the BOM server. Strange.

```r
: stop("\nThe server with the bulletin files is not responding.", "Please retry again later.\n") at /home/travis/build/ropensci/bomrang/R/get_ag_bulletin.R:111
```

**Comment by HughParsonage** [comment]
This error is the strangest imo:

``` r
httr::http_error("ftp://ftp.bom.gov.au/anon/gen/fwo/IDN11060.xml")
#> Warning in parse_http_status(lines[[1]]): NAs introduced by coercion
#> Warning: Failed to parse headers:
#> 220-
#> 220-                              Disclaimer
#> 220-
#> 220-You accept all risks and responsibility for losses, damages, costs and
#> 220-other consequences resulting directly or indirectly from using this site and
#> 220-any information or material available from it.
#> 220-
#> 220-To the maximum permitted by law, the Bureau of Meteorology excludes all
#> 220-liability to any person arising directly or indirectly from using this
#> 220-site and any information or material available from it.
#> 220-
#> 220-Always Check the Information
#> 220-
#> 220-
#> 220-. is general information provided as part of the Bureau of Meteorology's
#> 220-  statutory role in the dissemination of information relating to
#> 220-  meteorology.
#> 220-. is subject to the uncertainties of scientific and technical research
#> 220-. may not be accurate, current or complete
#> 220-. is subject to change without notice
#> 220-. is not a substitute for independent professional advice and users
#> 220-  should obtain any appropriate professional advice relevant to their
#> 220-  particular circumstances
#> 220-. the material on this web site may include the views or recommendations
#> 220-  of third parties, which do not necessarily reflect the views of the
#> 220-  Bureau of Meteorology or indicate its commitment to a particular course of
#> 220-  action.
#> 220 
#> 331 Please specify the password.
#> 230 Login successful.
#> 257 "/"
#> 250 Directory successfully changed.
#> 250 Directory successfully changed.
#> 250 Directory successfully changed.
#> 213 20180325095713
#> 200 Switching to Binary mode.
#> 213 688346
#> 350 Restart position accepted (0).
#> [1] FALSE
```

**Comment by adamhsparks** [comment]
Indeed. I'd not seen that one yet.

**Pull request merged**
